---
    - name: Configure Server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regex: '^Server=.*$'
        line: "Server={{ ZabbixCore }},{{ Proxy }},{{ ProxyDev }}"

    - name: Configure ServerActive
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regex: '^# ServerActive=.*$'
        line: 'ServerActive={{ ZabbixCore }},{{ Proxy }},{{ ProxyDev }}'

    - name: Create AllowKey
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        line: 'AllowKey=system.run[*]'
...
