---
  - name: Download Zabbix Agent on {{ ansible_netbios_name }}
    win_get_url:
      url:  https://cdn.zabbix.com/zabbix/binaries/stable/5.0/5.0.7/zabbix_agent-5.0.7-windows-amd64-openssl.msi
      dest: C:\install

  - name: Uninstall Zabbix Agent on {{ ansible_netbios_name }}
    win_package:
      path: 'C:\install\zabbix_agent-5.0.7-windows-amd64-openssl.msi'
      state: absent
...

